# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20160228_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.CharField(default=datetime.datetime(2016, 2, 29, 19, 20, 10, 893543, tzinfo=utc), max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=2, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
