# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_seat_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Seat')),
            ],
        ),
    ]
