# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_customuser_booth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='casted_vote',
            field=models.BooleanField(default=False),
        ),
    ]
