# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_customuser_casted_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='vote_counted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='vote_counted',
            field=models.BooleanField(default=False),
        ),
    ]
