# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20160312_0911'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booth',
            unique_together=set([('id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set([('id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set([('id', 'name')]),
        ),
    ]
