# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_auto_20160325_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=10, null=True),
        ),
    ]
