# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0021_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_election_staff',
        ),
    ]
